version: '2'

services:
  client:
    build: ./client/
    ports:
      - "3000:3000"
    command: "npm start"
    depends_on:
      - server
  server:
    build: ./server/
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb+srv://rishabh:rishabh@cluster0.kaxxnnq.mongodb.net/mgmt_db?retryWrites=true&w=majority
    command: "npm start"